### ISSUE TITLE
Doc : how many requests?

### ISSUE THREAD

**Issue by Deleplace** [siadat/benchttp#3]
- Usage says to "use `-n 1000` to benchmark 1000 requests
- But the Options says `-n` is the `max-number-of-requests`, why doesn't look like the same thing
- And when I run with `-n 4`  I only send 2 requests.

So, no effective way of specifying the number of requests to send?

**Comment by siadat** [comment]
@Deleplace It used to support setting both `-d` and `-n`. The benchmark would stop when either one of the limits reached (duration or number). That's why the option said max number of requests.

I removed the support for setting both flags to simplify the usage. I exit with a fatal error when both flags are set. Feel free to re-open if you think supporting both flags would be useful and I will bring it back.
